plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testImplementation 'com.codeborne:selenide:7.15.0'
    testImplementation("net.datafaker:datafaker:2.5.4")
}

test {
    useJUnitPlatform()
}